apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-root
  name: sample-root
spec:
  ports:
  - name: 80-8080
    port: 9081
    protocol: TCP
    targetPort: 5178
  - name: https
    protocol: TCP
    port: 9043
    targetPort: 5178
  selector:
    app: sample-root
  type: LoadBalancer
status:
  loadBalancer: {}
  
