apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-root
  name: sample-root
spec:
  ports:
  - name: 80-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-root
  type: LoadBalancer
status:
  loadBalancer: {}
  
